### ISSUE TITLE
consider add get method in Map.

### ISSUE THREAD

**Issue by fastwei** [dingmaotu/mql4-lib#11]
Great job! there is no get method in Map interface,but pop() work.it would be better if add get method as java.
Order *o=map.get("800100");

**Comment by dingmaotu** [comment]
This is the same as use `[]` operator. I think `[]` is clearer than `get`. But `get` can be useful if it takes a second parameter like Python dict, get("a", "b") means if "a" exists then return the corresponding value; if not, return "b" instead. I will add this feature.
