### ISSUE TITLE
consider add isEmpty() method for Collection(Map,List,Vector).

### ISSUE THREAD

**Issue by fastwei** [dingmaotu/mql4-lib#13]
consider add isEmpty() method for Collection(Map,List,Vector).
in real complex ea,may be we have many Collection Group.
eg: 
Vector hedgeOneGroup;
Vector hedgeTwoGroup;
Vector buyGroup;
Vector sellGroup;
Vector limitGroup;
other....

when we check group for manage other group,we need isEmpty().

**Comment by dingmaotu** [comment]
I am pretty there is an `isEmpty` method. Please read carefully or at least test it out before opening a issue.

**Comment by fastwei** [comment]
I read code again,parent class Collection have virtual method isEmpty().i just search code in Vector and Set before.
