### ISSUE TITLE
How can I  make HashMap  with m_owner = true?

### ISSUE THREAD

**Issue by janckerchen** [dingmaotu/mql4-lib#15]
There is a class member declared HashMap<>, how can I make m_owner=true in order to auto release RuleNode* value?

```c++
class RuleManager {

  HashMap<string, RuleNode*> ruleNodes_;  // m_owner=false by default
 HashMap<string, RuleNode*> ruleNodes_(NULL, true); // bad grammar in mql5

}
```

**Comment by dingmaotu** [comment]
You need to to the initialization in the constructor like in C++
```MQL5
class RuleManager {
public:
    RuleManager():ruleNodes_(NULL,true) {...}
}
```

**Comment by janckerchen** [comment]
yes,  works, I am stupid.

Is it possible use reference in HashMap?  like  HashMap<string, RuleNode> or HashMap<string, RuleNode&>

**Comment by dingmaotu** [comment]
Simple answer is no. Just use pointer, it is the same.

If you want to use HashMap<string,RuleNode>, RuleNode class should have value semantics, meaning it must have copy/assignment constructors. It is not efficient to use it this way.

**Comment by janckerchen** [comment]
thanks a lot
