### ISSUE TITLE
OrderManager Typo

### ISSUE THREAD

**Issue by JJJHawk** [dingmaotu/mql4-lib#16]
![grafik](https://user-images.githubusercontent.com/34318142/34920837-a594fb2c-f979-11e7-9302-9ea4f7203984.png)

Hi Ding Li,

greetings from Germany :-)

This is my very first contribution to GitHub. Didn't find another way than putting up a screenshot.
I try hard to use your Lib which I find very good. But still have massive problems to get into the code.

**Comment by dingmaotu** [comment]
Oh, this is a CRITICAL bug! Thank you for reporting this!
