### ISSUE TITLE
Adding a comment in the manager

### ISSUE THREAD

**Issue by pplomba** [dingmaotu/mql4-lib#19]
Hi... it's woonder to insert the comments management in the OrderManager....
some Mql programmers use this for retain some variables
Regards

Line 36:          ` ObjectAttr(string,comment,Comment);`
...
Line 178:         `
 int ticket=OrderSend(s,cmd,Math::roundUpToMultiple(lots,MINLOT),
                        price,m_slippage,
                        OS::N(s,stoploss),
                        OS::N(s,takeprofit),
                        m_comment,m_magic,0,m_color[cmd&1]);
`

**Comment by dingmaotu** [comment]
I will add an optional parameter comment to all ordering commands as users may want to use different comments for different orders
