### ISSUE TITLE
consider reverting #27

### ISSUE THREAD

**Issue by yerden** [dingmaotu/mql4-lib#28]
Issues with pull request #27:
* build is broken since `Nil` constant is unknown;
* if NULL constant was on @marfer's mind then the introduced check is redundant. `SafeDelete()` checks the pointer by `CheckPointer()` and does nothing with NULL pointer.

@dingmaotu: please check the build is ok before accepting pulls.

**Comment by marfer** [comment]
Hi, Nil constant is defined in RespBytes.mqh, it's a singleton that are used to encode NULLs to RESP format. If you clear RespArray it also delete this NULLs encoder through `SafeDelete()`, and on next time, we got Bad Pointer crash in MT

**Comment by yerden** [comment]
Oh, I see, my bad.

Then, I guess, we have a dependency issue here. `RespArray.mqh` doesn't `#include` `RespBytes.mqh`. Everybody who uses RespArray should include RespBytes.mqh from now on.

Or we can include it right in `RespArray.mqh`?

**Comment by marfer** [comment]
Exactly, probably need to include `RespBytes.mqh`  to `RespArray.mqh` or change include order in `Resp.mqh` or move Nil definition to `RespArray.mqh`. I'm not so strong in mql, and any advise will be helpful from you guys. 
Sorry that I've broke the build :smile:

**Comment by yerden** [comment]
As stated in README: "To use the RESP protocol, you need to include Mql/Format/Resp.mqh".  Looks like now the build is ok, it was my `#include` mistake.

**Comment by dingmaotu** [comment]
@yerden @marfer Thanks for discussing the issue and it is necessary to clarify things and expose problems. Though including Resp.mqh directly does not break the build but I think it is a good practice to include RespBytes.mqh in RespArray.mqh as the Nil entity is referenced. I will make the change.
