### ISSUE TITLE
questions on interfaces behaviour

### ISSUE THREAD

**Issue by yerden** [dingmaotu/mql4-lib#29]
Must the method implementation check for `m_owned` and do `SafeDelete()`?
https://github.com/dingmaotu/mql4-lib/blob/e7608fbb99a263e0d197686b9a5777ea599d87cb/Collection/Collection.mqh#L136

For example, here, you say:
https://github.com/dingmaotu/mql4-lib/blob/e7608fbb99a263e0d197686b9a5777ea599d87cb/Collection/Vector.mqh#L112

What's the expected behaviour here?

**Comment by dingmaotu** [comment]
The exact behavior of this method should be checking for owning status and delete the element if necessary. If T is not a pointer, it is not necessary. But for the Vector case, what I was thinking is that if I can pass a pointer to the container, then I at least have a reference of the object and if I want to remove it from the container then I may not want to invalidate my reference at the same time. So the behavior here is not standard but it is reasonable. I don't know how to reconcile this obvious conflict. Do you have any idea?

**Comment by yerden** [comment]
If `Collection` class has public `m_owned` flag then we have to support it in every inherited implementation. Thus,  if `m_owned` is set, `Vector` implementation MUST destroy the element which is thrown out of it. Otherwise, there's no point in having `m_owned` flag in the first place. So must do every other derived class. So I don't think I get your point here :wink:

Globally, I think that the library must have consistent, non-contradictory API throughout all the code base. Ideally, all these caveats must be documented, or at least (which is more important) all derived classes must display the same behaviour hinted by their ancestors.

**Comment by dingmaotu** [comment]
OK, I think you are right. I will fix the inconsistency ASAP.

**Comment by yerden** [comment]
Hi, any success? I'd be glad if you process the PR backlog out there :smile:

**Comment by dingmaotu** [comment]
Not yet. Sorry for the slow response to your PR. I am extremely busy since I changed my job... I will try to process your PRs tonight. Thanks for your contribution.
