### ISSUE TITLE
Can I make thee strategy optimization process based on GPU using OpenCL ?

### ISSUE THREAD

**Issue by JafferWilson** [dingmaotu/mql4-lib#39]
Hi, I have tried your repository. It will good. But I thought that it will help me in making my program run using GPU via OpenCL. But could not understand as my Optimization is utilizing all the CPU instead of GPU.  
Can you help me in making optimization process work with GPU?

**Comment by dingmaotu** [comment]
No. The optimizer is implemented in MT4 Terminal and it is not configurable for users. The OpenCL support allows you to use the power of GPU in your MQL programs but you need to write them. There is no automatic way to use GPU for your optimization.
