### ISSUE TITLE
HashMap使用求助

### ISSUE THREAD

**Issue by fleyfley** [dingmaotu/mql4-lib#40]
HashMap能否在 value 中存放 List 对象？
例如：HashMap<string, LinkedList<int>>
场景如下：
在 order 遍历的时候，取出订单注释，按订单注释来做分组。
Map 的 key 是 comment，value 是分组的订单号。
写了一个 test，编译一下很多错误。
请帮忙给下实现的建议，谢谢。

**Comment by dingmaotu** [comment]
理论上可以的，这样：`HashMap<string,LinkedList<Order*>*>`

**Comment by dingmaotu** [comment]
LinkedList的元素类型是简单类型或者指针

**Comment by fleyfley** [comment]
谢谢，有段时间没上 github，我回头试试看。
