### ISSUE TITLE
hi. got a problem in the example.    TestOrderPool.mq4 

### ISSUE THREAD

**Issue by chhcuo** [dingmaotu/mql4-lib#42]
// for simplicity, I will not use the Lang/Script class
void OnStart()
  {
   **LinkedList**<Order*> list;  (OrderList error)
   int total= OrdersTotal();//TradingPool::total();(here.. i don`t know, just use the mql offical....)
   for(int i=0; i<total; i++)
     {
      if(OrderSelect(i,SELECT_BY_POS,MODE_TRADES)) (here.. i don`t know, just use the mql offical....)
        {
         OrderPrint(); // to compare with Order.toString
         list.push(new Order());
        }
     }

   PrintFormat("There are %d orders. ",list.size());

===============
plz update TradingPool()  in ur convience. thx lots.

**Comment by dingmaotu** [comment]
See the latest README. The commit used to close this issue has some problems.

**Comment by chhcuo** [comment]
thank u. digmaotu.
