### ISSUE TITLE
Issue with multiple indicator buffer access

### ISSUE THREAD

**Issue by sdejonghe** [dingmaotu/mql4-lib#43]
Hello,
I'm testing your framework and it is awesome.
But I have an issue when I need to access an indicator with multiples buffers.
Is it possible to explain if it is possible to access other buffer that the one in for example Demarker indicator
double            operator[](const int index) {return ExtMainBuffer[ArraySize(ExtMainBuffer)-index-1];}
What about if I need to access ExtMaxBuffer[]?
Is it a limit in the design and do I need to create some getter to access supplementaries buffers?
Best Regards,

**Comment by dingmaotu** [comment]
You can just create another getter to use other buffers ^_^
