### ISSUE TITLE
New update to MT4 1210 2019.9.6, LinkedList.mqh ERROR. 

### ISSUE THREAD

**Issue by chhcuo** [dingmaotu/mql4-lib#46]
hi, sorry to tell you: 

when the newest versiong MT4(build1210 2019.9.6,), the following errors occur.

https://github.com/dingmaotu/mql4-lib/ 

LinkedList.mqh
 line 188:

`_clear(void)`
'clear' - unexpected token, probably type is missing?	LinkedList.mqh	188	13
'clear' - function already defined and has different type	LinkedList.mqh	188	13

**Comment by dingmaotu** [comment]
Thank you for reporting this, I will make a fix asap.

**Comment by chhcuo** [comment]
Guy u r welcome. thank you so much for your kindness and the opensouce proj.
thank u. May u wonderful life and good luck.
