### ISSUE TITLE
'=' - type mismatch	GlobalVariable.mqh

### ISSUE THREAD

**Issue by thomas795** [dingmaotu/mql4-lib#54]
after upgrading to Metatrader terminal 4 build 1280 my Zero MQ implementation from Darwinx (DWX_ZeroMQ_Server_v2.0.1_RC8.mq4) project will no longer compile. i receive this error:

'=' - type mismatch	GlobalVariable.mqh

in line 292   "m_hm=new HM;"

Please help! :)

**Comment by 7iW** [comment]
I was able to resolve this issue by replacing the Darwinex Zero MQ implementation with the Zero MQ implementation from  <https://github.com/dingmaotu/mql-zmq>.

**Comment by thomas795** [comment]
Thanks alot 7iW that worked! :)

**Comment by Martian4x** [comment]
Thanks it worked. So the solution is to replace the entire dwx-zeromq-connector from @dingmaotu not just the two changed files for the solution of the previous errors. 👍
