### ISSUE TITLE
'=' - type mismatch	GlobalVariable.mqh	292	12

### ISSUE THREAD

**Issue by aleksandermajos** [dingmaotu/mql4-lib#55]
Hi!Excellent work!In MT5 work flawessly in MT4 before new update also work as well.Now MT4 Build 1280 makes this error in the title above.I Know MT4/5 very little.Using Your library to push data to Python and .NET.

**Comment by dingmaotu** [comment]
MQL has buggy implementation of templates. Sometimes the code is OK and sometimes there is type mismatch error. In latest version this file compiled fine.
