### ISSUE TITLE
Compilation error in 'HelloWorldServer.mq4' file

### ISSUE THREAD

**Issue by barmenteros** [dingmaotu/mql4-lib#61]
First of all, congratulations on such an amazing job!

I tried to compile the file '[HelloWorldServer.mq4](https://github.com/dingmaotu/mql-zmq/blob/f9bf8d94a34194a4fe79ae625779226900fe8657/Scripts/ZeroMQGuideExamples/Chapter1/HelloWorldServer.mq4)' in ***MetaEditor version 5 build 2401*** but I get the following error:
```c
'=' - type mismatch GlobalVariable.mqh 292 12
```
In '[GlobalVariable.mqh](https://github.com/dingmaotu/mql4-lib/blob/1d00831274cda667360b13963ffffa6d5a09daf4/Lang/GlobalVariable.mqh)', the line in question is this one: 
```c
m_hm = new HM;
```
Could it be that the pointer is expecting to receive a 'HandleManager' object but is receiving a 'Context' object? Or am I missing something in the implementation and use of this example?

Could you help me with this?

Thanks in advance

**Comment by dingmaotu** [comment]
I compiled in build 3914 and found no error. Maybe it was a compiler bug and got fixed in newer versions. In Context class, `HM` is ContextHandleManager, which is a subclass (or implementation) of interface HandleManager<intptr_t>, and should be OK to be assigned to its parent.

**Comment by barmenteros** [comment]
You're right. Compiled in build 3915 with no issues. Thank you for your response and for the excellent job in this library too.
