### ISSUE TITLE
Can i use this libary for trade a account without EA

### ISSUE THREAD

**Issue by UsernameGitiHub** [dingmaotu/mql4-lib#62]
Hello, can you tell me if it is possible with the help of this libary to trade mt4 accounts without need to put a EA on chart, justwith useing mt4 login details? I would guess its not possible but please somebody let me know if it is possible.

**Comment by mashida** [comment]
No, you can not.

**Comment by UsernameGitiHub** [comment]
Thank you to let me know. if somebody know such a open source solution would be nice to know it.

**Comment by mashida** [comment]
There is no open source _library to help trade MT4 accounts without need to put a EA on a chart_ because the only program that trades MT4 accounts is Expert Advisor.

**Comment by UsernameGitiHub** [comment]
Yes it looks like that, i also did not find any open source solution for mt4, i only see some payed offers in the internet which i think work with dll functions. but for mt5 i think there is a better solution, where you can use just login details from a mt5 account and then you can trade the account with functions.
