### ISSUE TITLE
does this lib support mac os m1

### ISSUE THREAD

**Issue by joshua-xia** [dingmaotu/mql4-lib#66]
I am using mac os m1 and both mt4 and mt5 can run on this os system

but it seems this mql4-lib and mt4-zmq, mt4-python integration failed to work on mac os m1

Do you have interested in implementing on the mac os m1?

Thanks!

**Comment by dingmaotu** [comment]
I'd like to but I don't have an m1 mac now. The DLLs used are compiled for x86 or x64 so they will not work out of box.

**Comment by joshua-xia** [comment]
> I'd like to but I don't have an m1 mac now. The DLLs used are compiled for x86 or x64 so they will not work out of box.

I already used another way to integrate mql4 and python, I close this issue
