### ISSUE TITLE
LinkedList Initialization in MQL4

### ISSUE THREAD

**Issue by i3130002** [dingmaotu/mql4-lib#67]
I hope this message finds you well. I am writing to inquire about the current functionality of your library, specifically about MQL4.

I have encountered some difficulties in initializing a LinkedList. My attempts so far have been unsuccessful, and I'm unsure if this is due to an issue on my end. To clarify, here is the code snippet I used:

``` cpp
LinkedList<int> intList;
```

If the problem lies with my approach, I would greatly appreciate it if you could provide a complete example code to guide me.

I would also like to take this opportunity to express my gratitude for the immense effort and dedication that has gone into developing this remarkable library. Your hard work is sincerely appreciated.

**Comment by rex1122rr** [comment]
You should use the CLinkedList check: https://www.mql5.com/en/docs/standardlibrary/generic/clinkedlist

**Comment by dingmaotu** [comment]
@i3130002 Your code should compile if the lib is properly installed. What is the error reported by the compiler? There is a complete example in the README (though it uses LinkedList<Order*>). It should work with int.

**Comment by i3130002** [comment]
Thanks, I gave it a try and it seems to be working this time. 

The following is a sample code I used to test this time:
```C++
#property strict 
#include <stdlib.mqh>
#include "Collection/LinkedList.mqh"

LinkedList<int> intList;

int OnInit() {
  intList.push(1);
  printer();
  intList.push(2);
  printer();
  intList.push(11);
  printer();
  intList.push(3);
  printer();
  intList.removeAt(2);
  printer();
  return (INIT_SUCCEEDED);
}

void OnDeinit(const int reason) {
}

void OnTick() {
}

void printer(){
    string res = "";
    for(Iter<int> it(intList); !it.end(); it.next())
     {
      int o=it.current();
      res +="," + IntegerToString(o);
     }
     Print(res);
}
```
