### ISSUE TITLE
selectByTicket Member Function Not Defined

### ISSUE THREAD

**Issue by Ken-LiuL** [dingmaotu/mql4-lib#7]
There is a call for OrderPool::selectByTicket(ticket) in MqlCommand.mqh,  however,  a declaration of this function can not be found  in  the abstract class OrderPool

**Comment by dingmaotu** [comment]
This issue should go to the mt4-server project...I pushed the update there. This should be fixed now.

**Comment by hphade** [comment]
> This issue should go to the mt4-server project...I pushed the update there. This should be fixed now.

thanks mate!
