### ISSUE TITLE
Is "Order Access" part in readme compatible Mql5?

### ISSUE THREAD

**Issue by janckerchen** [dingmaotu/mql4-lib#8]
Mql5 had dropped  api  like  OrderXXX() ,  "Order Access" part seems not compatible Mql5

**Comment by dingmaotu** [comment]
No, it is not. As the introduction says: "Except for trading related classes, you can use the library on MetaTrader5." That's basically all code under the `Trade` directory. Order management is very different in MetaTrader5. I have not come up with a cross version abstraction of order management functions. Maybe a separate module for MT5 order management would be more practical.
